# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fenetre_Ajout.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Fenetre_Ajout(object):
    def setupUi(self, Fenetre_Ajout):
        Fenetre_Ajout.setObjectName("Fenetre_Ajout")
        Fenetre_Ajout.resize(1094, 663)
        self.Ajout_Btn_Contacts = QtWidgets.QPushButton(Fenetre_Ajout)
        self.Ajout_Btn_Contacts.setGeometry(QtCore.QRect(40, 50, 93, 28))
        self.Ajout_Btn_Contacts.setObjectName("Ajout_Btn_Contacts")
        self.Ajout_Btn_Clients = QtWidgets.QPushButton(Fenetre_Ajout)
        self.Ajout_Btn_Clients.setGeometry(QtCore.QRect(250, 50, 93, 28))
        self.Ajout_Btn_Clients.setObjectName("Ajout_Btn_Clients")
        self.Ajout_Btn_Packages = QtWidgets.QPushButton(Fenetre_Ajout)
        self.Ajout_Btn_Packages.setGeometry(QtCore.QRect(490, 50, 93, 28))
        self.Ajout_Btn_Packages.setObjectName("Ajout_Btn_Packages")
        self.Ajout_Btn_Contracts = QtWidgets.QPushButton(Fenetre_Ajout)
        self.Ajout_Btn_Contracts.setGeometry(QtCore.QRect(720, 50, 93, 28))
        self.Ajout_Btn_Contracts.setObjectName("Ajout_Btn_Contracts")
        self.Ajout_Btn_Bills = QtWidgets.QPushButton(Fenetre_Ajout)
        self.Ajout_Btn_Bills.setGeometry(QtCore.QRect(960, 50, 93, 28))
        self.Ajout_Btn_Bills.setObjectName("Ajout_Btn_Bills")
        self.Ajout_Tableau = QtWidgets.QListWidget(Fenetre_Ajout)
        self.Ajout_Tableau.setGeometry(QtCore.QRect(40, 130, 1011, 361))
        self.Ajout_Tableau.setObjectName("Ajout_Tableau")
        self.Ajout_Btn_Valider = QtWidgets.QPushButton(Fenetre_Ajout)
        self.Ajout_Btn_Valider.setGeometry(QtCore.QRect(442, 540, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Ajout_Btn_Valider.setFont(font)
        self.Ajout_Btn_Valider.setObjectName("Ajout_Btn_Valider")

        self.retranslateUi(Fenetre_Ajout)
        QtCore.QMetaObject.connectSlotsByName(Fenetre_Ajout)

    def retranslateUi(self, Fenetre_Ajout):
        _translate = QtCore.QCoreApplication.translate
        Fenetre_Ajout.setWindowTitle(_translate("Fenetre_Ajout", "Form"))
        self.Ajout_Btn_Contacts.setText(_translate("Fenetre_Ajout", "Contacts"))
        self.Ajout_Btn_Clients.setText(_translate("Fenetre_Ajout", "Clients"))
        self.Ajout_Btn_Packages.setText(_translate("Fenetre_Ajout", "Packages"))
        self.Ajout_Btn_Contracts.setText(_translate("Fenetre_Ajout", "Contracts"))
        self.Ajout_Btn_Bills.setText(_translate("Fenetre_Ajout", "Bills"))
        self.Ajout_Btn_Valider.setText(_translate("Fenetre_Ajout", "Valider l\'ajout"))
