# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fenetre_Supprimer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Fenetre_Supprimer(object):
    def setupUi(self, Fenetre_Supprimer):
        Fenetre_Supprimer.setObjectName("Fenetre_Supprimer")
        Fenetre_Supprimer.resize(1078, 639)
        self.Supprimer_Btn_Contracts = QtWidgets.QPushButton(Fenetre_Supprimer)
        self.Supprimer_Btn_Contracts.setGeometry(QtCore.QRect(710, 60, 93, 28))
        self.Supprimer_Btn_Contracts.setObjectName("Supprimer_Btn_Contracts")
        self.Supprimer_Tableau = QtWidgets.QListWidget(Fenetre_Supprimer)
        self.Supprimer_Tableau.setGeometry(QtCore.QRect(30, 140, 1011, 361))
        self.Supprimer_Tableau.setObjectName("Supprimer_Tableau")
        self.Supprimer_Btn_Clients = QtWidgets.QPushButton(Fenetre_Supprimer)
        self.Supprimer_Btn_Clients.setGeometry(QtCore.QRect(240, 60, 93, 28))
        self.Supprimer_Btn_Clients.setObjectName("Supprimer_Btn_Clients")
        self.Supprimer_Btn_Valider = QtWidgets.QPushButton(Fenetre_Supprimer)
        self.Supprimer_Btn_Valider.setGeometry(QtCore.QRect(410, 540, 251, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Supprimer_Btn_Valider.setFont(font)
        self.Supprimer_Btn_Valider.setObjectName("Supprimer_Btn_Valider")
        self.Supprimer_Btn_Packages = QtWidgets.QPushButton(Fenetre_Supprimer)
        self.Supprimer_Btn_Packages.setGeometry(QtCore.QRect(480, 60, 93, 28))
        self.Supprimer_Btn_Packages.setObjectName("Supprimer_Btn_Packages")
        self.Supprimer_Btn_Contacts = QtWidgets.QPushButton(Fenetre_Supprimer)
        self.Supprimer_Btn_Contacts.setGeometry(QtCore.QRect(30, 60, 93, 28))
        self.Supprimer_Btn_Contacts.setObjectName("Supprimer_Btn_Contacts")
        self.Supprimer_Btn_Bills = QtWidgets.QPushButton(Fenetre_Supprimer)
        self.Supprimer_Btn_Bills.setGeometry(QtCore.QRect(950, 60, 93, 28))
        self.Supprimer_Btn_Bills.setObjectName("Supprimer_Btn_Bills")

        self.retranslateUi(Fenetre_Supprimer)
        QtCore.QMetaObject.connectSlotsByName(Fenetre_Supprimer)

    def retranslateUi(self, Fenetre_Supprimer):
        _translate = QtCore.QCoreApplication.translate
        Fenetre_Supprimer.setWindowTitle(_translate("Fenetre_Supprimer", "Form"))
        self.Supprimer_Btn_Contracts.setText(_translate("Fenetre_Supprimer", "Contracts"))
        self.Supprimer_Btn_Clients.setText(_translate("Fenetre_Supprimer", "Clients"))
        self.Supprimer_Btn_Valider.setText(_translate("Fenetre_Supprimer", "Valider la suppression"))
        self.Supprimer_Btn_Packages.setText(_translate("Fenetre_Supprimer", "Packages"))
        self.Supprimer_Btn_Contacts.setText(_translate("Fenetre_Supprimer", "Contacts"))
        self.Supprimer_Btn_Bills.setText(_translate("Fenetre_Supprimer", "Bills"))
