# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fenetre_VueGloable.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Fenetre_VueGlobale(object):
    def setupUi(self, Fenetre_VueGlobale):
        Fenetre_VueGlobale.setObjectName("Fenetre_VueGlobale")
        Fenetre_VueGlobale.resize(1085, 734)
        self.VueGlobale_ComboBox = QtWidgets.QComboBox(Fenetre_VueGlobale)
        self.VueGlobale_ComboBox.setGeometry(QtCore.QRect(10, 110, 201, 41))
        self.VueGlobale_ComboBox.setObjectName("VueGlobale_ComboBox")
        self.VueGlobale_ComboBox.addItem("")
        self.VueGlobale_ComboBox.addItem("")
        self.VueGlobale_ComboBox.addItem("")
        self.VueGlobale_ComboBox.addItem("")
        self.VueGlobale_ComboBox.addItem("")
        self.VueGlobale_Instruction = QtWidgets.QTextBrowser(Fenetre_VueGlobale)
        self.VueGlobale_Instruction.setGeometry(QtCore.QRect(10, 30, 861, 51))
        self.VueGlobale_Instruction.setObjectName("VueGlobale_Instruction")
        self.VueGlobale_Tableau = QtWidgets.QTableWidget(Fenetre_VueGlobale)
        self.VueGlobale_Tableau.setGeometry(QtCore.QRect(10, 191, 1061, 531))
        self.VueGlobale_Tableau.setObjectName("VueGlobale_Tableau")
        self.VueGlobale_Tableau.setColumnCount(0)
        self.VueGlobale_Tableau.setRowCount(0)

        self.retranslateUi(Fenetre_VueGlobale)
        QtCore.QMetaObject.connectSlotsByName(Fenetre_VueGlobale)

    def retranslateUi(self, Fenetre_VueGlobale):
        _translate = QtCore.QCoreApplication.translate
        Fenetre_VueGlobale.setWindowTitle(_translate("Fenetre_VueGlobale", "Form"))
        self.VueGlobale_ComboBox.setItemText(0, _translate("Fenetre_VueGlobale", "Clients"))
        self.VueGlobale_ComboBox.setItemText(1, _translate("Fenetre_VueGlobale", "Contacts"))
        self.VueGlobale_ComboBox.setItemText(2, _translate("Fenetre_VueGlobale", "Packages"))
        self.VueGlobale_ComboBox.setItemText(3, _translate("Fenetre_VueGlobale", "Contracts"))
        self.VueGlobale_ComboBox.setItemText(4, _translate("Fenetre_VueGlobale", "Bills"))
        self.VueGlobale_Instruction.setHtml(_translate("Fenetre_VueGlobale", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Veuillez choisir ci-dessous une table à propos de laquelle vous voulez avoir une vision globale :</span></p></body></html>"))
