# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fenetre_Accueil.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Page_Accueil(object):
    def setupUi(self, Page_Accueil):
        Page_Accueil.setObjectName("Page_Accueil")
        Page_Accueil.resize(1079, 733)
        self.Widget_General = QtWidgets.QWidget(Page_Accueil)
        self.Widget_General.setObjectName("Widget_General")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Widget_General)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Frame_Visuel = QtWidgets.QFrame(self.Widget_General)
        self.Frame_Visuel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_Visuel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_Visuel.setObjectName("Frame_Visuel")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Frame_Visuel)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Image_Logo = QtWidgets.QLabel(self.Frame_Visuel)
        self.Image_Logo.setText("")
        self.Image_Logo.setPixmap(QtGui.QPixmap(":/newPrefix/Logo_Blink.jpeg"))
        self.Image_Logo.setObjectName("Image_Logo")
        self.verticalLayout_3.addWidget(self.Image_Logo, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.Frame_Texte = QtWidgets.QFrame(self.Frame_Visuel)
        self.Frame_Texte.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_Texte.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_Texte.setObjectName("Frame_Texte")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Frame_Texte)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Texte_Accueil = QtWidgets.QTextBrowser(self.Frame_Texte)
        self.Texte_Accueil.setObjectName("Texte_Accueil")
        self.verticalLayout_2.addWidget(self.Texte_Accueil)
        self.verticalLayout_3.addWidget(self.Frame_Texte)
        self.verticalLayout.addWidget(self.Frame_Visuel)
        self.Frame_Boutons = QtWidgets.QFrame(self.Widget_General)
        self.Frame_Boutons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_Boutons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_Boutons.setObjectName("Frame_Boutons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Frame_Boutons)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Button_Recherche = QtWidgets.QPushButton(self.Frame_Boutons)
        self.Button_Recherche.setObjectName("Button_Recherche")
        self.horizontalLayout.addWidget(self.Button_Recherche)
        self.Button_Ajout = QtWidgets.QPushButton(self.Frame_Boutons)
        self.Button_Ajout.setObjectName("Button_Ajout")
        self.horizontalLayout.addWidget(self.Button_Ajout)
        self.Button_Retirer = QtWidgets.QPushButton(self.Frame_Boutons)
        self.Button_Retirer.setObjectName("Button_Retirer")
        self.horizontalLayout.addWidget(self.Button_Retirer)
        self.verticalLayout.addWidget(self.Frame_Boutons)
        Page_Accueil.setCentralWidget(self.Widget_General)
        self.menubar = QtWidgets.QMenuBar(Page_Accueil)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1079, 26))
        self.menubar.setObjectName("menubar")
        Page_Accueil.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Page_Accueil)
        self.statusbar.setObjectName("statusbar")
        Page_Accueil.setStatusBar(self.statusbar)

        self.retranslateUi(Page_Accueil)
        QtCore.QMetaObject.connectSlotsByName(Page_Accueil)

    def retranslateUi(self, Page_Accueil):
        _translate = QtCore.QCoreApplication.translate
        Page_Accueil.setWindowTitle(_translate("Page_Accueil", "MainWindow"))
        self.Texte_Accueil.setHtml(_translate("Page_Accueil", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Bienvenue dans la base de données de </span><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">Blink Digital Agency </span><span style=\" font-size:10pt; font-weight:600;\">!</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Vous pouvez choisir un menu ci-dessous pour interagir avec la base de données</span></p></body></html>"))
        self.Button_Recherche.setText(_translate("Page_Accueil", "Recherche"))
        self.Button_Ajout.setText(_translate("Page_Accueil", "Ajouter des données"))
        self.Button_Retirer.setText(_translate("Page_Accueil", "Retirer des données"))
import ressources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Page_Accueil = QtWidgets.QMainWindow()
    ui = Ui_Page_Accueil()
    ui.setupUi(Page_Accueil)
    Page_Accueil.show()
    sys.exit(app.exec_())